In [1]:
import numpy as np

An array can be represented by many dimensions, each dimension has different names

In [2]:
# Dimension 0 (escalar)
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [3]:
# Dimension 1 (vector)
vector = np.array([29, 27, 33, 31, 38, 42, 38])
print(vector)

[29 27 33 31 38 42 38]


In [4]:
# Dimension 2 (Mtriz)
matrix = np.array(
    [
        [24, 29, 11],
        [25, 31, 33],
        [27, 28, 34]
    ]
)

In [5]:
tensor = np.array(
    [
        [
            [12, 33, 14, 53],
            [56, 23, 124, 525],
            [56, 999, 1345, 234]
        ],
        [
            [452, 1355, 2353, 124],
            [235, 526, 257, 257],
            [368, 461, 4675, 3256]
        ],
        [
            [2357, 235, 46 ,23],
            [356, 235, 235, 2],
            [35, 56778, 2356, 32]
        ]
    ]
)
print(tensor)
print(tensor.ndim)

[[[   12    33    14    53]
  [   56    23   124   525]
  [   56   999  1345   234]]

 [[  452  1355  2353   124]
  [  235   526   257   257]
  [  368   461  4675  3256]]

 [[ 2357   235    46    23]
  [  356   235   235     2]
  [   35 56778  2356    32]]]
3


In [6]:
array_arange = np.arange(1, 11)
print(array_arange)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
eye_matrix = np.eye(7)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [9]:
diag = np.diag([34, 13, 56, 11, 90, 00, 14])
print(diag)

[[34  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0]
 [ 0  0 56  0  0  0  0]
 [ 0  0  0 11  0  0  0]
 [ 0  0  0  0 90  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 14]]


In [11]:
random = np.random.random([4, 5])
print(random)

[[0.88343133 0.32232126 0.00888487 0.94642684 0.65214303]
 [0.16356129 0.05717934 0.81520033 0.14604795 0.03700846]
 [0.44384989 0.05584747 0.2845577  0.6987445  0.16079799]
 [0.86032393 0.52574944 0.48935783 0.66011465 0.62873674]]
