In [1]:
import numpy as np

In [3]:
array = np.array([10, 20, 30, 40, 50])
print(array[1])
print(array[len(array) - 1])

20
50


In [4]:
print(array[1:4])
print(array[1:77])

[20 30 40]
[20 30 40 50]


In [5]:
array > 25

array([False, False,  True,  True,  True])

In [6]:
array[array > 25]

array([30, 40, 50])

In [8]:
array[[3, 0, 2]]

array([40, 10, 30])

In [11]:
matrix = np.random.randint(1, 100, size=(4, 3))
print(matrix)

[[91 65 61]
 [ 7 81 15]
 [67 60 68]
 [22 54 10]]
