In [1]:
import numpy as np

In [4]:
prices = np.array([100, 200, 300])
discount = np.array([0.9])

discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [6]:
prices2 = np.random.randint(100, 500, size=(3, 3))
discount2 = np.array([10, 20, 30])

print(prices2)

[[468 419 201]
 [280 479 496]
 [396 181 124]]


In [7]:
discount_prices2 = prices2 + discount2
print(discount_prices2)

[[478 439 231]
 [290 499 526]
 [406 201 154]]


In [13]:
# Logic ops
array = np.arange(1, 6)
print(np.all(array > -10))  # It means all values from array are grather than -10
print(np.any(array > 4))  # It means if any value is grather than 4

True
True


In [14]:
# Concatenate one or more arrays to get only one
array_a = np.arange(1, 4)
array_b = np.arange(4, 7)

concatenate = np.concat((array_a, array_b))
print(concatenate)

[1 2 3 4 5 6]


In [18]:
# Stacking
stacked_v = np.vstack((array_a, array_b))
stacked_h = np.hstack((array_a, array_b))

print(stacked_v)
print()
print(stacked_h)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [21]:
# Split
array_c = np.arange(1, 11)
split_array = np.split(array_c, 2)  # Dividie arrays by 2 (in this case)

print(split_array)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
