In [1]:
import numpy as np

In [9]:
survey_responses = np.array(
    [
        "bueno", "excelente", "malo",
        "bueno", "malo", "excelente",
        "bueno", "bueno", "malo",
        "excelente", "excelente", "excelente"
    ]
)

In [10]:
print(np.unique(survey_responses))
print(np.unique(survey_responses, return_counts=True))

['bueno' 'excelente' 'malo']
(array(['bueno', 'excelente', 'malo'], dtype='<U9'), array([4, 5, 3]))


In [11]:
array_x = np.arange(10)
view_y = array_x[1:3]

print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]


In [12]:
array_x[1:3] = [10, 11]
print(array_x)
print(view_y)

[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [14]:
array_x2 = np.arange(10)
copy_x2 = array_x2[[1, 2]]

print(array_x2)
print(copy_x2)

array_x2[1:3] = [21, 22]

print(array_x2)
print(copy_x2)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 21 22  3  4  5  6  7  8  9]
[1 2]
