In [1]:
import numpy as np

In [3]:
matrix = np.array(
    [
        [11, 24, 45],
        [90, 77, 81],
        [29, 31, 49]
    ]
)
transposed_matrix = matrix.T

print(matrix)
print()
print(transposed_matrix)

[[11 24 45]
 [90 77 81]
 [29 31 49]]

[[11 90 29]
 [24 77 31]
 [45 81 49]]


## Reshape

change the shape of an array without change their data

In [4]:
array = np.arange(1, 13)
reshaped_array = array.reshape(3, 4)

print(array)
print()
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
reversed_array = array[::-1]
print(array)
print()
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[12 11 10  9  8  7  6  5  4  3  2  1]


In [7]:
print(matrix)

[[11 24 45]
 [90 77 81]
 [29 31 49]]


In [8]:
flattened_matrix = matrix.flatten()
print(flattened_matrix)

[11 24 45 90 77 81 29 31 49]
