In [1]:
import numpy as np

In [2]:
months = np.array(
    [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    ]
)

product_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
prodcut_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
product_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

In [4]:
print(len(product_A), len(prodcut_B), len(product_C), len(months))

12 12 12 12


In [5]:
stacked_data = np.stack((product_A, prodcut_B, product_C))
print(stacked_data)

[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]


In [8]:
# Total sales for each product
total_sale_A = product_A.sum()
total_sale_B = prodcut_B.sum()
total_sale_C = product_C.sum()

print(f"The total sales for each product are A: {total_sale_A}, B: {total_sale_B}, C: {total_sale_C}")

The total sales for each product are A: 2750, B: 3090, C: 3720


In [10]:
# Sales per month
month_sales = np.array([
    stacked_data[::, 0].sum(), stacked_data[::, 1].sum(), stacked_data[::, 2].sum(),
    stacked_data[::, 3].sum(), stacked_data[::, 4].sum(), stacked_data[::, 5].sum(),
    stacked_data[::, 6].sum(), stacked_data[::, 7].sum(), stacked_data[::, 8].sum(),
    stacked_data[::, 9].sum(), stacked_data[::, 10].sum(), stacked_data[::, 11].sum()
])

print(month_sales)

[ 530  630  720  810  770  770  740  780  860  910  990 1050]


In [12]:
# Sales per year
print(stacked_data.sum())
print(month_sales.sum())

9560
9560
