In [1]:
import numpy as np

In [2]:
A = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)
B = np.array(
    [
        [5, 6],
        [7, 8]
    ]
)

In [4]:
# add
add = A + B

print(A)
print()
print(B)
print()
print(add)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 6  8]
 [10 12]]


In [7]:
# subtraction
subtraction = B - A
print(subtraction)

[[4 4]
 [4 4]]


In [8]:
# multiply
multiply = A.dot(B)
multiply2 = B.dot(A)

print(multiply)
print()
print(multiply2)

[[19 22]
 [43 50]]

[[23 34]
 [31 46]]


In [9]:
# determinant
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

print(det_A)
print()
print(inv_A)

-2.0000000000000004

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
# solve Ax = B
b = np.array([9, 11])
x = np.linalg.solve(A, b)

print(x)

[-7.  8.]
